#!/bin/sh

set -e -u

cp -va tests README.rst "$AUTOPKGTEST_TMP"/
cd "$AUTOPKGTEST_TMP"

for py in $(py3versions -s 2>/dev/null); do
	echo "Running testsuite with $py:"
	$py -m unittest tests/*.py
done
